# Generated by Django 4.2 on 2026-02-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the request was approved', null=True)),
                ('due_date', models.DateField(blank=True, help_text='When the book should be returned', null=True)),
                ('returned_at', models.DateTimeField(blank=True, help_text='When the book was returned', null=True)),
                ('reason_for_rejection', models.TextField(blank=True, help_text='Reason for rejecting the request', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='books.book')),
            ],
            options={
                'verbose_name': 'Borrow Request',
                'verbose_name_plural': 'Borrow Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
