# Generated by Django 4.2 on 2026-02-24 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['reader'], name='borrowing_b_reader__719e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['book'], name='borrowing_b_book_id_08fc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status'], name='borrowing_b_status_af39f5_idx'),
        ),
    ]
