# Generated by Django 4.2 on 2026-02-26  

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='requested_days',
            field=models.PositiveIntegerField(
                choices=[
                    (7, '7 days'),
                    (10, '10 days'),
                    (14, '14 days'),
                    (21, '21 days'),
                ],
                blank=True,
                null=True,
                help_text='Number of days reader would like to borrow the book',
            ),
        ),
    ]
