# Generated by Django 4.2 on 2026-02-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('borrow_approved', 'Borrow Request Approved'), ('borrow_rejected', 'Borrow Request Rejected'), ('book_available', 'Book Became Available'), ('borrow_due_soon', 'Borrow Due Soon'), ('borrow_overdue', 'Borrow Overdue'), ('review_added', 'Review Added'), ('role_change_approved', 'Role Change Approved'), ('role_change_rejected', 'Role Change Rejected'), ('book_approved', 'Book Approved'), ('book_rejected', 'Book Rejected')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='books.book')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
