# Generated by Django 4.2 on 2026-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('borrow_request', 'Borrow Request'), ('borrow_approved', 'Borrow Request Approved'), ('borrow_rejected', 'Borrow Request Rejected'), ('book_available', 'Book Became Available'), ('borrow_due_soon', 'Borrow Due Soon'), ('borrow_overdue', 'Borrow Overdue'), ('review_added', 'Review Added'), ('role_change_approved', 'Role Change Approved'), ('role_change_rejected', 'Role Change Rejected'), ('book_approved', 'Book Approved'), ('book_rejected', 'Book Rejected')], max_length=50),
        ),
    ]
