# Generated by Django 4.2 on 2026-02-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the book')),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('biography', 'Biography'), ('history', 'History'), ('self-help', 'Self-Help'), ('poetry', 'Poetry'), ('children', 'Children'), ('young-adult', 'Young Adult'), ('educational', 'Educational'), ('other', 'Other')], help_text='Genre of the book', max_length=50)),
                ('language', models.CharField(default='English', help_text='Language of the book', max_length=50)),
                ('publication_date', models.DateField(help_text='Date of publication')),
                ('publisher', models.CharField(blank=True, help_text='Publisher of the book', max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN number', max_length=20, null=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Book cover image', null=True, upload_to='book_covers/')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file of the book (for download)', null=True, upload_to='book_files/')),
                ('availability', models.CharField(choices=[('borrow', 'Available for Borrowing'), ('download', 'Available for Download'), ('both', 'Both Borrowing and Download'), ('unavailable', 'Currently Unavailable')], default='borrow', help_text='How the book is available', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Publication status of the book', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('pages', models.IntegerField(blank=True, help_text='Number of pages', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Book Wishlist',
                'verbose_name_plural': 'Book Wishlists',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, help_text='Whether the user has completed reading the book')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed reading the book', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='books.book')),
            ],
            options={
                'verbose_name': 'Reading History',
                'verbose_name_plural': 'Reading Histories',
                'ordering': ['-added_at'],
            },
        ),
    ]
