# Generated by Django 4.2 on 2026-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_author',
            field=models.CharField(default='Unknown', help_text='Original author who wrote the book', max_length=255),
        ),
    ]
