# Generated by Django 4.2 on 2026-02-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_book_original_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Download',
                'verbose_name_plural': 'Book Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookdownload',
            index=models.Index(fields=['user'], name='books_bookd_user_id_01d04c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookdownload',
            index=models.Index(fields=['book'], name='books_bookd_book_id_6b5877_idx'),
        ),
    ]
