# Generated by Django 4.2 on 2026-02-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_file_blob_book_file_mime_book_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF/EPUB file of the book (for download)', null=True, upload_to='book_files/', verbose_name='PDF/EPUB file'),
        ),
    ]
